# Generated by Django 4.2.16 on 2024-09-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='curp',
        ),
    ]
