# Generated by Django 4.2.16 on 2024-09-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_useraccount_curp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='colony',
        ),
    ]
