# Generated by Django 4.2.16 on 2024-09-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
