# Generated by Django 4.2.16 on 2024-09-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='guard_name',
        ),
    ]
